# Generated by Django 4.1.7 on 2024-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0002_alter_sender_sender_mobile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sender",
            name="sender_ssn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sender",
            name="sender_zip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
