# Generated by Django 4.1.7 on 2023-12-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_account', models.CharField(max_length=100)),
                ('point_of_payment', models.CharField(max_length=100)),
                ('mode_pay_receiver', models.CharField(max_length=100)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_payment_info', to='receiver.receiver')),
            ],
        ),
    ]
