version: "3.8"
services:
  backend:
    build: .

    volumes:
      - ./app:/app

    restart: unless-stopped
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "8080:8080"
    # Generate static css and js, apply migrations and start server
    # command: sh -c "python manage.py runserver 0.0.0.0:8080"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
