version: "3.8"
services:


  backend:
    build: .

    volumes:
      - ./app:/app

    restart: unless-stopped

    ports:
      - "8000:8000"  
    # Generate static css and js, apply migrations and start server
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"




