# Generated by Django 4.1.7 on 2023-12-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DecimalField(decimal_places=2, max_digits=20)),
                ('end', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_payment_info', to='user.admin')),
            ],
        ),
    ]
