# Generated by Django 4.1.7 on 2023-12-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_payment_info', to='user.admin'),
        ),
    ]
