# Generated by Django 4.1.7 on 2023-12-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agency_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='rate',
            new_name='default_rate',
        ),
        migrations.AddField(
            model_name='agency',
            name='max_rate',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agency',
            name='min_rate',
            field=models.DecimalField(decimal_places=2, default=124, max_digits=20),
            preserve_default=False,
        ),
    ]
