# Generated by Django 4.1.7 on 2023-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_alter_receiver_receiver_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='receiver_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='receiver_mother_maiden',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
