# Generated by Django 4.1.7 on 2023-12-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DecimalField(decimal_places=2, max_digits=20)),
                ('end', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
