# Generated by Django 4.1.7 on 2023-12-18 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('commission', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agency_payment_info', to='agency.agency'),
            preserve_default=False,
        ),
    ]
