# Generated by Django 4.1.7 on 2023-12-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_rename_rate_agency_default_rate_agency_max_rate_and_more'),
        ('commission', '0003_commission_agency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('end', 'agency')},
        ),
    ]
