# Generated by Django 4.1.7 on 2023-12-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sender', '0001_initial'),
        ('receiver', '0001_initial'),
        ('order', '0001_initial'),
        ('payment_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_infos', to='payment_info.paymentinfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to='receiver.receiver'),
        ),
        migrations.AddField(
            model_name='order',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senders', to='sender.sender'),
        ),
    ]
