# Generated by Django 4.1.7 on 2023-12-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='sender_phone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
